repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.4
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args:
          - --line-length=110
-   repo: https://gitlab.com/PyCQA/flake8
    rev: '3.8.3'
    hooks:
    -   id: flake8
-   repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
    -   id: nbstripout
        files: ".ipynb"
