name: book_rec
channels:
  - conda-forge
  - fastai
dependencies:
  - python
  - pip
  - pre-commit
  - pytorch
  - fastai>2.0.0

  - pip:
    - black==20.8b1
    - flake8==3.8.3
    - isort==5.5.4
    - annoy
