name: book_rec
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pre-commit
  - pytorch
  - scikit-learn
  - streamlit
  - spacy

  - pip:
    - black==20.8b1
    - flake8==3.8.3
    - isort==5.5.4
    - annoy
